index:
   path: /
   controller: App\Controller\ToDoController::list

save_todo:
   path: /save
   methods: POST
   controller: App\Controller\ToDoController::post

edit_todo:
   path: /save/{id}
   methods: PATCH
   controller: App\Controller\ToDoController::patch